name: 🔥 Migrate database

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  migration:
    name: 🔑 Migrate database
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_DATABASE: ${{ github.ref_name == 'main' && secrets.DB_DATABASE || format('pr_{0}', github.event.number) }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download deps
        run: npm ci

      - name: Create database
        continue-on-error: true
        run: npm run db:create

      - name: Migrate database
        run: npm run db:migrate
